name: Regression Testing Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '00 4 * * *'

jobs:
  Windows:
    runs-on: windows-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 21
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Run Tests
        continue-on-error: true
        run: mvn test clean test
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: secrets.MAIL_CONNECTION
          server_address: smtp.office365.com
          server_port: 587
          secure: true
          username: contact@qweira.com
          password: Mm123456@@
          subject: Github Actions job result
          to: wa.nagib86@gmail.com
          body: Build job of Qweira_App completed successfully!
          attachments: test-output/emailable-report.html
