name: Qweira App Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Clean Maven and target folder
        run: |
          mvn clean
          rm -rf target
          rm -rf test-output

      - name: Build and test Qweira App
        run: mvn test

      - name: Generate emailable report
        run: mvn surefire-report:report-only

      - name: Upload emailable report
        uses: actions/upload-artifact@v2
        with:
          name: emailable-report
          path: target/site/surefire-report.html
